#   __                      __             
#  /\ \                    /\ \__          
#  \ \ \____    ___     ___\ \ ,_\   ____  
#   \ \ '__`\  / __`\  / __`\ \ \/  /',__\ 
#    \ \ \L\ \/\ \L\ \/\ \L\ \ \ \_/\__, `\
#     \ \_,__/\ \____/\ \____/\ \__\/\____/
#      \/___/  \/___/  \/___/  \/__/\/___/ 
#
#  The clean Bootstrap theme for Juliet !

# Site specific params (mandatory)

title: My brand new blog !
description: "Foodporn for everybody ! Yay !"

# Build informations (mandatory)

baseurl: ""
theme: boots
